export default {
  // Internal errors
  FETCH_FAILED: 'FETCH_FAILED',
  // From API
  INVALID_QUERY_PARAMS: 'INVALID_QUERY_PARAMS',
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND'
};
