---
- hosts: all
  become: yes

  vars:
    static_files_path: "/var/www/{{ domain_name }}"

  tasks:
    - name: Include variables
      include_vars: variables.yml

    - name: Get time
      shell: "date +%Y%m%d%H%M"
      register: timestamp

    - name: Copy static files
      copy:
        src: ../../web/dist/
        dest: "{{ static_files_path }}/static_{{ timestamp.stdout }}/"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_user }}"
        mode: 0755

    - name: Update Nginx server block
      template:
        src: templates/nginx_config.j2
        dest: "/etc/nginx/sites-available/{{ domain_name }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Tidy up to last 3 releases
      shell: rm -rf `ls -t | awk 'NR>3'`
      args:
        chdir: "{{ static_files_path }}/"
        executable: /bin/bash
      warn: False

  handlers:
    - import_tasks: handlers.yml
