---
- name: Deploy static
  import_playbook: deploy_static.yml

- hosts: all
  become: yes

  tasks:
    - name: Include variables
      include_vars: variables.yml

    - name: Add link to site-enabled
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}"
        dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
        owner: root
        group: root
        state: link
      notify: reload nginx

    - name: Create Gunicorn log folder
      file:
        path: "{{ gunicorn_log_dir }}"
        state: directory
        owner: root
        group: "{{ nginx_user }}"
        mode: 0775

    - name: Create Gunicorn config
      template:
        src: templates/gunicorn_config.j2
        dest: "{{ gunicorn_config }}"
        owner: "{{ project_user }}"
        group: "{{ project_user }}"
        mode: 0644

    - name: Create Gunicorn systemd service
      template:
        src: templates/gunicorn_systemd.j2
        dest: "/etc/systemd/system/{{ gunicorn_service }}.service"
        owner: root
        group: root
        mode: 0644
      notify: reload systemctl

    - name: Ensure Gunicorn is started and enabled to start at boot.
      service:
        name: "{{ gunicorn_service }}"
        state: started
        enabled: yes

  handlers:
    - import_tasks: handlers.yml
