from .game import Game

COL_GAME_ID = 0
COL_GAME_DATE = 1
COL_IS_REGULAR = 2
COL_WIN_TYPE = 3
COL_HOME_TEAM_ID = 4
COL_AWAY_TEAM_ID = 5
COL_HOME_GOALS = 6
COL_HOME_GOALS_PERIOD1 = 7
COL_HOME_GOALS_PERIOD2 = 8
COL_HOME_GOALS_PERIOD3 = 9
COL_HOME_SHOTS = 10
COL_HOME_PP_GOALS = 11
COL_HOME_PP_OPPORTUNITIES = 12
COL_HOME_FACE_OFF_WINS = 13
COL_HOME_BLOCKED = 14
COL_HOME_HITS = 15
COL_HOME_PENALTY_MINUTES = 16
COL_AWAY_GOALS = 17
COL_AWAY_GOALS_PERIOD1 = 18
COL_AWAY_GOALS_PERIOD2 = 19
COL_AWAY_GOALS_PERIOD3 = 20
COL_AWAY_SHOTS = 21
COL_AWAY_PP_GOALS = 22
COL_AWAY_PP_OPPORTUNITIES = 23
COL_AWAY_FACE_OFF_WINS = 24
COL_AWAY_BLOCKED = 25
COL_AWAY_HITS = 26
COL_AWAY_PENALTY_MINUTES = 27
COL_FACE_OFF_TAKEN = 28

GAME_WIN_TYPE_REGULAR = 0
GAME_WIN_TYPE_OVERTIME = 1
GAME_WIN_TYPE_SHOOTOUT = 2

WIN_TYPE_MAP = {
    Game.WIN_TYPE_REGULAR: GAME_WIN_TYPE_REGULAR,
    Game.WIN_TYPE_OVERTIME: GAME_WIN_TYPE_OVERTIME,
    Game.WIN_TYPE_SHOOTOUT: GAME_WIN_TYPE_SHOOTOUT
}
