### Get all seasons

GET http://localhost:5000/api/season/all
Accept: */*
Cache-Control: no-cache

### Get current season

GET http://localhost:5000/api/season/current
Accept: */*
Cache-Control: no-cache

### Get season stats

GET http://localhost:5000/api/season/stats?sid=1&stype=reg
Accept: */*
Cache-Control: no-cache

### Get season stats. Invalid season id

GET http://localhost:5000/api/season/stats?sid=15&stype=reg
Accept: */*
Cache-Control: no-cache
# Response code: 404

### Get season stats. Invalid season type

GET http://localhost:5000/api/season/stats?sid=5&stype=nn
Accept: */*
Cache-Control: no-cache
# Response code: 400

### Get season penalties chart

GET http://localhost:5000/api/season/charts/penalties?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get all skaters stats for season

GET http://localhost:5000/api/stats/skaters?sid=4&stype=reg
Accept: */*
Cache-Control: no-cache

### Get all goalies stats for season

GET http://localhost:5000/api/stats/goalies?sid=4&stype=reg
Accept: */*
Cache-Control: no-cache

### Get all teams stats for season

GET http://localhost:5000/api/stats/teams?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get stats for all seasons

GET http://localhost:5000/api/stats/seasons
Accept: */*
Cache-Control: no-cache

### Get team stats for season

GET http://localhost:5000/api/team/15/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get team stats for season. Invalid team id

GET http://localhost:5000/api/team/1500/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache
# Response code: 404

### Get all teams for season

GET http://localhost:5000/api/teams?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get team stats for all seasons

GET http://localhost:5000/api/team/15/all-stats
Accept: */*
Cache-Control: no-cache

### Get team seasons

GET http://localhost:5000/api/team/54/seasons
Accept: */*
Cache-Control: no-cache

### Get team players stats for season

GET http://localhost:5000/api/team/15/players/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get team point progress chart for season

GET http://localhost:5000/api/team/15/charts/points-progress?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get team penalties chart for season

GET http://localhost:5000/api/team/15/charts/penalties?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get skater stats for season

GET http://localhost:5000/api/skater/8478402/stats?sid=4&stype=reg
Accept: */*
Cache-Control: no-cache

### Get skater stats for season. Invalid skater id

GET http://localhost:5000/api/skater/1/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache
# Response code: 404

### Get all skaters for season

GET http://localhost:5000/api/skaters?sid=4&stype=reg
Accept: */*
Cache-Control: no-cache

### Get skater stats for all seasons

GET http://localhost:5000/api/skater/8448208/all-stats
Accept: */*
Cache-Control: no-cache

### Get skater seasons

GET http://localhost:5000/api/skater/8474149/seasons
Accept: */*
Cache-Control: no-cache

### Get skater point progress chart for season

GET http://localhost:5000/api/skater/8474149/charts/points-progress?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get skater penalties chart for season

GET http://localhost:5000/api/skater/8474149/charts/penalties?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get goalie stats for season

GET http://localhost:5000/api/goalie/8469608/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get goalie stats for season. Invalid goalie id

GET http://localhost:5000/api/goalie/1/stats?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache
# Response code: 404

### Get all goalies for season

GET http://localhost:5000/api/goalies?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get goalie stats for all seasons

GET http://localhost:5000/api/goalie/8471750/all-stats
Accept: */*
Cache-Control: no-cache

### Get goalie seasons

GET http://localhost:5000/api/goalie/8469608/seasons
Accept: */*
Cache-Control: no-cache

### Compare teams for season

GET http://localhost:5000/api/team/53/compare/20?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Compare skaters for season

GET http://localhost:5000/api/skater/8478402/compare/8471490?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Compare goalies for season

GET http://localhost:5000/api/goalie/8476945/compare/8471679?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get standings

GET http://localhost:5000/api/teams/standings?sid=3&stype=reg
Accept: */*
Cache-Control: no-cache

### Get playoff

GET http://localhost:5000/api/teams/play-off?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

### Get penalty drew by chart

GET http://localhost:5000/api/skaters/charts/penalty-drew-by?sid=4&stype=reg
Accept: */*
Cache-Control: no-cache

### Get scorer duos rating

GET http://localhost:5000/api/ratings/scorer-duos?sid=5&stype=reg
Accept: */*
Cache-Control: no-cache

###
